spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5436/notificationdb
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8083
